//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Abandonos
    {
        public int Id { get; set; }
        public int ExpedienteId { get; set; }
        public string TipoResolucion { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Opciones { get; set; }
        public System.DateTime Fecha1 { get; set; }
        public System.DateTime Fecha2 { get; set; }
        public System.DateTime Fecha3 { get; set; }
        public System.DateTime Fecha4 { get; set; }
        public string Observaciones { get; set; }
    }
}
