//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anotacion
    {
        public int Id { get; set; }
        public int ExpedienteId { get; set; }
        public Nullable<int> TitularId { get; set; }
        public string NuevoTitular { get; set; }
        public string Direccion { get; set; }
        public Nullable<int> PaisId { get; set; }
    }
}
