//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnotacionEnExpedientes
    {
        public int Id { get; set; }
        public int ExpedienteId { get; set; }
        public Nullable<int> TipoDeAnotacionId { get; set; }
        public int EnExpedienteId { get; set; }
        public int EnRegistro { get; set; }
        public string Raya { get; set; }
        public int EstatusId { get; set; }
        public Nullable<int> ActualizadoPorUsuarioId { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
        public Nullable<int> AgenteId { get; set; }
        public int TipoDeRegistroId { get; set; }
    
        public virtual Expediente Expedientes { get; set; }
    }
}
