//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anualidad
    {
        public int Id { get; set; }
        public int ExpedienteId { get; set; }
        public int NumeroAnualidad { get; set; }
        public bool EsRenovacion { get; set; }
        public System.DateTime FechaVencimiento { get; set; }
        public decimal Valor { get; set; }
        public string Recibo { get; set; }
        public System.DateTime FechaRecibo { get; set; }
        public int UsuarioId { get; set; }
        public string Observaciones { get; set; }
        public System.DateTime FechaAnualidad { get; set; }
    }
}
