//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AporteAudiovisual
    {
        public int Id { get; set; }
        public int ExpedienteId { get; set; }
        public string Director { get; set; }
        public string Genero { get; set; }
        public string Clase { get; set; }
        public string Metraje { get; set; }
        public string Duracion { get; set; }
    }
}
