//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bitacora
    {
        public int Id { get; set; }
        public int ExpedienteId { get; set; }
        public string METADATA { get; set; }
        public System.DateTime FechaDeCambio { get; set; }
        public int CambioPorUsuarioId { get; set; }
        public string Razon { get; set; }
    
        public virtual Expediente Expedientes { get; set; }
    }
}
