//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CronologiaDocto
    {
        public int Id { get; set; }
        public int CronologiaId { get; set; }
        public Nullable<System.Guid> Llave { get; set; }
        public string JSONDOC { get; set; }
        public string HTMLDOC { get; set; }
        public System.DateTime FechaActualizacion { get; set; }
        public int ActualizadoPorUsuarioId { get; set; }
        public Nullable<bool> EsTitulo { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
