//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DerechoDeAutor
    {
        public int Id { get; set; }
        public int ExpedienteId { get; set; }
        public string Titulo { get; set; }
        public string Traduccion { get; set; }
        public Nullable<int> Paginas { get; set; }
        public string Formato { get; set; }
        public string LugarEdicion { get; set; }
        public Nullable<System.DateTime> FechaEdicion { get; set; }
        public string LugarEraPublicacion { get; set; }
        public Nullable<System.DateTime> FechaPublicacion { get; set; }
        public string Editor { get; set; }
        public string AnioCreacion { get; set; }
        public Nullable<int> PaisOrigenId { get; set; }
        public Nullable<bool> EsInedita { get; set; }
        public Nullable<bool> EsPublicada { get; set; }
        public Nullable<bool> EsOriginaria { get; set; }
        public Nullable<bool> EsDerivada { get; set; }
        public Nullable<bool> EsIndividual { get; set; }
        public Nullable<bool> EsColectiva { get; set; }
        public Nullable<bool> EsEnColaboracion { get; set; }
        public string OtraClasificacionAplicable { get; set; }
        public string VersionesAutorizadas { get; set; }
        public string OtraInfoQueIdentifique { get; set; }
        public string SoporteMaterial { get; set; }
        public Nullable<int> Registro { get; set; }
        public string Libro { get; set; }
        public int Tomo { get; set; }
        public int Folio { get; set; }
    }
}
