//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expediente
    {
        public Expediente()
        {
            this.Bitacora = new HashSet<Bitacora>();
            this.Cronologia = new HashSet<Cronologia>();
            this.Marcas = new HashSet<Marca>();
            this.Renovaciones = new HashSet<Renovacion>();
            this.AnotacionEnExpedientes = new HashSet<AnotacionEnExpedientes>();
        }
    
        public int Id { get; set; }
        public int ModuloId { get; set; }
        public int TipoDeRegistroId { get; set; }
        public string Numero { get; set; }
        public System.DateTime FechaDeSolicitud { get; set; }
        public System.TimeSpan Hora { get; set; }
        public int EstatusId { get; set; }
        public System.DateTime FechaDeEstatus { get; set; }
        public int LeyId { get; set; }
        public Nullable<int> UbicacionId { get; set; }
        public Nullable<int> UbicacionUsuarioId { get; set; }
        public Nullable<System.DateTime> FechaTraslado { get; set; }
        public Nullable<int> ActualizadoPorUsuarioId { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
    
        public virtual ICollection<Bitacora> Bitacora { get; set; }
        public virtual ICollection<Cronologia> Cronologia { get; set; }
        public virtual ICollection<Marca> Marcas { get; set; }
        public virtual ICollection<Renovacion> Renovaciones { get; set; }
        public virtual ICollection<AnotacionEnExpedientes> AnotacionEnExpedientes { get; set; }
    }
}
