//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gaceta
    {
        public int Id { get; set; }
        public Nullable<int> ExpedienteId { get; set; }
        public Nullable<int> TipoDeRegistroId { get; set; }
        public string Numero { get; set; }
        public int GacetaSeccionId { get; set; }
        public System.DateTime FechaPublicacion { get; set; }
        public string JSONDOC { get; set; }
        public Nullable<bool> enabled { get; set; }
        public string HTMLDOC { get; set; }
        public Nullable<System.DateTime> FechaEdicto { get; set; }
    }
}
