//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LiterariasyArtisticas
    {
        public int Id { get; set; }
        public int ExpedienteId { get; set; }
        public string NombreDelEditor { get; set; }
        public string DireccionEditor { get; set; }
        public string NombreImprenta { get; set; }
        public string DireccionImprenta { get; set; }
        public string Edicion { get; set; }
        public string Tamano { get; set; }
        public string Clasificacion { get; set; }
    }
}
