//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObrasMusicalesyEscenicas
    {
        public int Id { get; set; }
        public int ExpedienteId { get; set; }
        public string Partitura { get; set; }
        public string Letra { get; set; }
        public string Genero { get; set; }
        public Nullable<bool> EsAutor { get; set; }
        public Nullable<bool> EsMusica { get; set; }
        public Nullable<bool> EsComercial { get; set; }
        public string ClaseGenero { get; set; }
        public string Duracion { get; set; }
    }
}
