//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patentes
    {
        public int Id { get; set; }
        public int ExpedienteId { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> Registro { get; set; }
        public Nullable<int> AgenteId { get; set; }
        public Nullable<int> anualidades { get; set; }
        public string Folio { get; set; }
        public string Tomo { get; set; }
        public string Resumen { get; set; }
        public Nullable<int> ClasificacionId { get; set; }
        public Nullable<int> RecibidoPorUsuarioId { get; set; }
        public Nullable<System.DateTime> FechaRecepcion { get; set; }
        public string Pct { get; set; }
        public Nullable<System.DateTime> Fecha_Pct { get; set; }
        public string Citaciones { get; set; }
    }
}
