//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permiso
    {
        public int Id { get; set; }
        public int UsuarioId { get; set; }
        public string Opcion { get; set; }
        public bool Acceso { get; set; }
        public int OtorgadoPorUsuarioId { get; set; }
    }
}
