//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Publicacion
    {
        public int Id { get; set; }
        public string expediente { get; set; }
        public Nullable<System.DateTime> fecha_edicto { get; set; }
        public Nullable<System.DateTime> fecha_publicacion { get; set; }
        public string distintivo { get; set; }
        public string titular { get; set; }
        public string clase { get; set; }
        public string mandatario { get; set; }
        public Nullable<System.DateTime> fecha_solicitud { get; set; }
        public string calidad { get; set; }
        public string pais { get; set; }
        public string productos { get; set; }
        public string firmado_por { get; set; }
        public string logotipo { get; set; }
        public string archivo { get; set; }
        public Nullable<int> tipo_edicto { get; set; }
        public string dir_comercial { get; set; }
    }
}
