//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Regla
    {
        public Regla()
        {
            this.Acciones = new HashSet<Acciones>();
            this.ReglaAcciones = new HashSet<ReglaAcciones>();
            this.ReglaDataForm = new HashSet<ReglaDataForm>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ActividadActualId { get; set; }
        public Nullable<int> EstadoActualId { get; set; }
        public int ActividadAEjecutarId { get; set; }
    
        public virtual ICollection<Acciones> Acciones { get; set; }
        public virtual ICollection<ReglaAcciones> ReglaAcciones { get; set; }
        public virtual ICollection<ReglaDataForm> ReglaDataForm { get; set; }
    }
}
