//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReglaDataForm
    {
        public int Id { get; set; }
        public int ReglaId { get; set; }
        public string Campo { get; set; }
        public string Etiqueta { get; set; }
        public int TypeId { get; set; }
        public string Colleccion { get; set; }
        public string Validacion { get; set; }
        public bool EsRequerido { get; set; }
    
        public virtual Regla Reglas { get; set; }
    }
}
