//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resolucion
    {
        public int Id { get; set; }
        public int ExpedienteId { get; set; }
        public string TipoResolucion { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Observaciones { get; set; }
        public string Opciones { get; set; }
        public string Otros { get; set; }
        public Nullable<System.DateTime> FechaNotificacion { get; set; }
        public Nullable<System.DateTime> FechaPublicacion { get; set; }
        public string Hora { get; set; }
    }
}
