//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Titulos
    {
        public int Id { get; set; }
        public int ExpedienteId { get; set; }
        public string TipoResolucion { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Observaciones { get; set; }
        public System.DateTime FechaAnotaciones { get; set; }
        public System.DateTime FechaConsecion { get; set; }
        public int Plazo { get; set; }
        public int Clasificacion { get; set; }
        public int Flag { get; set; }
        public Nullable<int> TipoDeAcuerdoId { get; set; }
        public string Acuerdo { get; set; }
        public Nullable<System.DateTime> FechaAcuerdo { get; set; }
    }
}
