//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuarioPublico
    {
        public int Id { get; set; }
        public string Cuenta { get; set; }
        public string Pwd { get; set; }
        public string Nombre { get; set; }
        public string Empresa { get; set; }
        public string Ciudad { get; set; }
        public string EstadoProvincia { get; set; }
        public string Telefonos { get; set; }
        public int PaisId { get; set; }
        public Nullable<bool> Suscripcion { get; set; }
        public string Spk { get; set; }
        public Nullable<System.DateTime> SpkExpiration { get; set; }
        public Nullable<System.DateTime> FechaSuscripcion { get; set; }
        public Nullable<System.DateTime> FechaCaducidad { get; set; }
        public string Direccion { get; set; }
    }
}
